name: cd

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
